Resources/ti.ui.switch.test.js

JIRA: https://jira.appcelerator.org/browse/TIMOB-9007

[TIMOB-9007] Add unit-test for Ti.UI.Switch default-value

---

Resources/ti.app.properties.test.js

**JIRA**: https://jira.appcelerator.org/browse/TIMOB-20506

[TIMOB-20506] Add unit-test for null-value in list

---

Resources/ti.ui.webview.test.js

JIRA: https://jira.appcelerator.org/browse/TIMOB-10488

[TIMOB-10488] Add unit-test for WebView "loading"

---

Resources/ti.ui.listview.test.js

**JIRA**: https://jira.appcelerator.org/browse/TIMOB-24085
**SDK**: https://github.com/appcelerator/titanium_mobile/pull/8565

[TIMOB-24085] Add test for iOS ListItem subtitles

---

Resources/ti.ui.label.test.js

**JIRA**: https://jira.appcelerator.org/browse/TIMOB-3408

[TIMOB-3408] Add test for justified text-alignment

---

Resources/ti.gesture.test.js

*JIRA*: https://jira.appcelerator.org/browse/TIMOB-7855

[TIMOB-7855] Update unit-tests for new parity in Ti.Gesture

---

Resources/ti.ui.window.test.js

- Implement a test case for `Ti.UI.Window.applyProperties()`
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-14285)

[TIMOB-14285] Include Ti.UI.Window.applyProperties() test case

---

Resources/ti.ui.webview.test.js

**JIRA**: https://jira.appcelerator.org/browse/TIMOB-24110

[TIMOB-24110] Add unit-test for Ti.UI.WebView.keyboardDisplayRequiresUserAction

---

Resources/ti.ui.label.test.js
Resources/ti.ui.textfield.test.js

**JIRA**: https://jira.appcelerator.org/browse/TIMOB-24153

[TIMOB-24153] iOS: Add unit-test for textfield padding

---

Resources/app.js
Resources/ti.app.test.js
Resources/ti.filesystem.test.js
Resources/ti.ui.test.js
Resources/ti.ui.textfield.test.js
Resources/ti.ui.webview.test.js

JIRA: https://jira.appcelerator.org/browse/TIMOB-23542

[TIMOB-23542] Add additional unit tests

---

Resources/ti.ui.view.test.js

**Test Case:**
Least complicated way of testing current pull request would be to copy changes into corresponding unit function:
1. copy `ti.ui.view.test.js` into titanium_mobile/tests/Resources with the changes
2. `touch app.js` in titanium_mobile/tests/Resources
3. require `ti.ui.view.test.js`
4. cd `titanium_mobile/build`
5. `node scons.js test android`
6. verify test passes/not fails.
`titanium_mobile/tests/Resources/app.js` _should look similar to this:_
```
var win = Ti.UI.createWindow({
backgroundColor: 'yellow'
});
win.open();
require('./ti-mocha');
var $results = [],
failed = false;
require('./ti.ui.view.test.js');
// add a special mocha reporter that will time each test run using
// our microsecond timer
function $Reporter(runner) {
var started,
title;
runner.on('suite', function …
```

[TIMOB-20586] fix ti-mocha suite backbroundColor/Image/Gradient test failure

---

Resources/app.js
Resources/ti.network.cookie.test.js

Test for Android: https://github.com/appcelerator/titanium_mobile/pull/9249
Output:
>   ✓ NETWORK_MOBILE 
>   ✓ NETWORK_LAN 
> **Titanium.Network.Cookie**
>   **✓ cookie isValid()** 
>   **✓ apiName** 
> Titanium.Network.HTTPClient
>   ✓ POST multipart/form-data containing Ti.Blob 
>   - callbackTestForPOSTMethod
>

[TIMOB-24988] Test for 'Add Ti.Network.Cookie isValid()'

---

Resources/ti.ui.tableview.test.js

- Refactor [TIMOB-15765](https://jira.appcelerator.org/browse/TIMOB-15765) to simplify the testing of max JNI references
- Speedup test and reduce log output

Refactor TIMOB-15765 test for JNI references

---

Resources/app.js
Resources/es6.class.js
Resources/es6.class.test.js
Resources/es6.import.test.js
Resources/es6.module.js

- Implement tests for `import` and `export` of modules

Add more ES6 tests

---

Resources/ti.ui.view.test.js

- Fix intermittent failure of `backgroundColor/Image` test

Android: Refactor ti.ui.view.test.js backgroundColor/Image test

---

Resources/ti.media.test.js
Resources/ti.ui.tabgroup.test.js
Resources/ti.ui.textarea.test.js
Resources/ti.ui.view.test.js

skip windows-specific broken tests:  https://jenkins.appcelerator.org/blue/organizations/jenkins/titanium-sdk%2Ftitanium_mobile_windows/detail/PR-1180/3/tests

skip windows-specific broken tests

---

scripts/test.js

We no longer uninstall apps by default, this flag makes it so we do

Add force uninstall flag for Windows

---

scripts/test.js

We no longer uninstall apps by default, this flag makes it so we do

[7_1_X]Add force uninstall flag for Windows #48

---

scripts/test.js

Workaround for https://jira.appcelerator.org/browse/TIMOB-25827

Dont force uninstall for wp-emulator

---

scripts/test.js

Cherry-pick #50 for master, workaround until [TIMOB-25827](https://jira.appcelerator.org/browse/TIMOB-25827) is addressed.

Dont force uninstall for wp-emulator (#50)

---

Resources/ti.buffer.test.js

See also: https://jenkins.appcelerator.org/blue/organizations/jenkins/titanium-sdk%2Ftitanium_mobile_windows/detail/PR-1235/2/tests

Skip buffer tests that's failing for Windows

---

scripts/test.js

This reverts commit a55b5018b6ec264cf7b869dc2f1c5aba26d6e595.

Revert "Clean before building (#58)"

---

scripts/package-lock.json

Seems like `package-lock.json` does not reflect latest state.

Update package-lock.json for npm ci

---

Resources/app.js
Resources/ti.android.service.interval.js
Resources/ti.android.service.normal.js
Resources/ti.android.service.test.js
scripts/test.js

**Summary:**
- Tests "interval" based services and "one-off" services.
- Tests APIs:
* `Ti.Android.createService()`
* `Ti.Android.startService()`
* `Ti.Android.stopService()`
**Note:**
This PR is needed to finish [TIMOB-16066](https://jira.appcelerator.org/browse/TIMOB-16066) for Titanium 7.3.0. Particularly the "scripts/test.js" which injects the Android services needed into the "tiapp.xml" so that I can complete the foreground service unit test feature.

Added Android "Service" unit tests

---

Resources/ti.ui.tableview.test.js

Reverts appcelerator/titanium-mobile-mocha-suite#68

Revert "Improve Window cleanup"

---

Resources/ti.ui.tableview.test.js

- Add timeout to allow previous window to close before opening another window
- Remove invalid test `appendSection and appendRow (TIMOB-25936)` that did not validate the issue and cannot be refactored too as the issue is UI related
- Although not necessary, I've added `win.close()` to all test cases

Fix ti.ui.tableview.test.js reliability

---

Resources/ti.media.audioplayer.test.js
Resources/ti.media.test.js
Resources/ti.ui.imageview.test.js

To fix test failures for Windows-Windows.

Skip tests missing for Windows

---

Resources/ti.ui.tableview.test.js

Some TableView tests are failing intermittently on Windows.

Skip unstable TableView tests for Windows

---

Resources/ti.ui.layout.test.js

[TIMOB-23372](https://jira.appcelerator.org/browse/TIMOB-23372)
Seems like TIMOB-23372 has been the issue again from some point of release (seems like long time ago).

Skip failing TIMOB-23372 tests for Windows

---

.eslintrc
Jenkinsfile
Resources/bootstraps/simple.bootstrap.js
Resources/bootstraps/ui.bootstrap.js
Resources/ti.blob.test.js
Resources/ti.bootstrap.test.js
Resources/ti.filesystem.file.test.js
Resources/ti.network.socket.tcp.test.js
Resources/ti.network.test.js
Resources/ti.ui.imageview.test.js
Resources/ti.ui.layout.test.js

Doing so might help reduce the Windows build breakage from migrating tests from the main repo
This wont do anything til appcelerator/jenkins_dsl/pull/74 is potentially merged

build: Add Jenkins job to mocha suite

---

Resources/ti.cloudpush.test.js
Resources/ti.map.test.js
Resources/ti.playservices.test.js
Resources/ti.ui.webview.test.js
modules/modules.xml

- Implement tests for `ti.playservices`
- Implement tests for `ti.cloudpush`
- Improve `ti.map` tests

test(android): implement missing module tests

---

Resources/ti.ui.webview.test.js

- Use `badssl.com` for SSL tests

fix: more webView fixes

---

Resources/ti.ui.webview.test.js

- Remove deprecated `getter` `setter` `zoomLevel` tests
- Fix SSL retrying

fix: various Ti.UI.WebView fixes

---

Resources/app.js

 fix(windows)(8_0_X): fix hang at startup on Windows (#131) 

---

Resources/ti.codec.test.js
package-lock.json
package.json

Closes #116, Closes #130, Closes #121, Closes #120, Closes #119

chore(deps): update dependencies

---

.eslintrc
plugins/mocha.test.support/hooks/hook.js

- Allow waking of multiple connected devices

fix: support waking multiple devices

---

Resources/ti.ui.activityindicator.test.js
Resources/ti.ui.layout.test.js
Resources/ti.ui.searchbar.test.js
Resources/ti.ui.textfield.test.js
Resources/ti.ui.view.test.js

migrate updated tests from Windows

fix(windows): apply precise checks for layout values

---

Resources/ti.blob.test.js
Resources/ti.map.test.js
Resources/ti.media.videoplayer.test.js
Resources/ti.network.httpclient.test.js
Resources/ti.ui.button.test.js
Resources/ti.ui.imageview.test.js
Resources/ti.ui.ios.navigationwindow.test.js
Resources/ti.ui.label.test.js
Resources/ti.ui.layout.test.js
Resources/ti.ui.listview.test.js
Resources/ti.ui.picker.test.js
Resources/ti.ui.scrollview.test.js
Resources/ti.ui.searchbar.test.js
Resources/ti.ui.tabgroup.test.js
Resources/ti.ui.tableview.test.js
Resources/ti.ui.test.js
Resources/ti.ui.textarea.test.js
Resources/ti.ui.textfield.test.js
Resources/ti.ui.view.test.js
Resources/ti.ui.webview.test.js
Resources/ti.ui.window.test.js
Resources/ti.utils.test.js

- Attempt to fix various issue with tests when running on Android 4.4 device
- This PR requires https://github.com/appcelerator/titanium_mobile/pull/10829 to be merged, where a window will not close if the activity has not been created when `close()` is called:
```JS
const win_a = Ti.UI.createWindow({ backgroundColor: 'green' });
const win_b = Ti.UI.createWindow({ backgroundColor: 'red' });
win_a.addEventListener('open', () => {
const view = Ti.UI.createWebView({ url: 'https://techcrunch.com/' });
win_b.add(view);
win_b.open();
win_b.close();
});
win_a.open();
```

fix: amend issues with tests

---

plugins/mocha.test.support/hooks/hook.js
scripts/junit.xml.ejs
scripts/test.js

- Workaround waking Android 4.4 devices
- Append device name to test, so it's clear what test ran on which device

fix(android): fixes for running on device

---

Resources/app.js
Resources/ti.ui.textarea.test.js
scripts/junit.xml.ejs
scripts/test.js

- Include OS version with device tests

impr: include os version

---

Resources/ti.ui.listview.test.js

- Close windows left open from tests

fix: close hanging windows

---

Resources/ti.ui.layout.test.js

- [TIMOB-25122](https://jira.appcelerator.org/browse/TIMOB-25122)
- [TIMOB-25123](https://jira.appcelerator.org/browse/TIMOB-25123)
Jenkins no longer fails these tests.

fix(windows): enable center precedence layout tests

---

Resources/ti.ui.layout.test.js

[TIMOB-25132](https://jira.appcelerator.org/browse/TIMOB-25132)
Fix broken TIMOB-23305 test

[TIMOB-25132] fix: Ti.UI.Layout TIMOB-23305 test failure

---

scripts/test.js

- Fix bug that prevented all tests from completing on all devices

fix(android): allow all device tests to complete

---

Resources/ti-mocha.js
Resources/ti.blob.test.js
Resources/ti.map.test.js
Resources/ti.media.videoplayer.test.js
Resources/ti.ui.button.test.js
Resources/ti.ui.imageview.test.js
Resources/ti.ui.label.test.js
Resources/ti.ui.layout.test.js
Resources/ti.ui.listview.test.js
Resources/ti.ui.maskedimage.test.js
Resources/ti.ui.picker.test.js
Resources/ti.ui.scrollableview.test.js
Resources/ti.ui.scrollview.test.js
Resources/ti.ui.searchbar.test.js
Resources/ti.ui.tabbedbar.test.js
Resources/ti.ui.tabgroup.test.js
Resources/ti.ui.tableview.test.js
Resources/ti.ui.test.js
Resources/ti.ui.textarea.test.js
Resources/ti.ui.textfield.test.js
Resources/ti.ui.view.test.js
Resources/ti.ui.webview.test.js
Resources/ti.ui.window.test.js
Resources/ti.utils.test.js

- Cherry-pick of https://github.com/appcelerator/titanium-mobile-mocha-suite/pull/174

chore(8_1_X): improve reliability of tests

---

Resources/ti.filesystem.file.test.js
Resources/ti.map.test.js
Resources/ti.media.videoplayer.test.js

https://jira.appcelerator.org/browse/TIMOB-27264
Re-enable some tests for Windows as Jenkins goes more stable after applying #182

test: enable Windows tests again

---

scripts/test.js

I didn't want to entirely revert #200, because It can be useful to test a `'test'` deploy type for testing encryption - but it's currently causing all master builds/PRs to crash on iOS due to https://jira.appcelerator.org/browse/TIMOB-27515
Going forward, I think we should just have the option to pass along the deploy type if we want to set it to `'test'` for PRs around encryption (or eventually as another parallel test run, once we get this crash fixed up)

feat: allow passing along deploy type argument optionally

---

Resources/ti.network.httpclient.test.js
Resources/ti.ui.webview.test.js

skip some tests that's failing on Windows

fix: skip failing tests on Windows

---

Resources/ti.network.httpclient.test.js
Resources/ti.ui.webview.test.js

fix: skip failing tests on Windows (#207)

---

Resources/ti.geolocation.test.js

https://jira.appcelerator.org/browse/TIMOB-25578
Note - Need to merge this PR first otherwise SDK PR https://github.com/appcelerator/titanium_mobile/pull/11350 will be failing as deprecated properties are removed.

fix: removed depricated properties  and updated to new
