appcelerator/titanium-mobile-mocha-suite

Resources/ti.ui.webview.test.js

Jenkins seems to fail because of my recent unit-test for iOS, because `Ti.UI.WebView.loading` is undefined on Android and it looks like Android doesn't even support the property. So two follow-up's:
1. What's about Windows, does it support the property?
2. We should update the docs in [here](https://github.com/appcelerator/titanium_mobile/blob/master/apidoc/Titanium/UI/WebView.yml#L538)
Thx! 🚀

Skip Ti.UI.WebView.loading test on Android for now

---

Resources/ti.ui.window.test.js

- Attempt to fix `close event is fired` by increasing the timeout before `close()` is called

Increase ti.ui.window.test.js 'close event is fired' timeout

---

scripts/package.json

Looks like there has been some problems in the last few build on running npm install and grabbing titanium from git, * should give us similar (although changes that are made without bumping the version wont be gotten)
https://jenkins.appcelerator.org/blue/organizations/jenkins/titanium-sdk%2Ftitanium_mobile/detail/master/450/pipeline/94

Pull titanium from npm

---

scripts/package.json

Looks like there has been some problems in the last few build on running npm install and grabbing titanium from git, * should give us what's on master

6_2_X Pull titanium from npm

---

Resources/ti.media.audioplayer.test.js
Resources/ti.media.sound.test.js

[TIMOB-25094](https://jira.appcelerator.org/browse/TIMOB-25094) and [TIMOB-25095](https://jira.appcelerator.org/browse/TIMOB-25095)
`Ti.Media.Sound` and `Ti.Media.AudioPlayer` should be asserting with the Ti namepsace for `apiName`.

[TIMOB-25094][TIMOB-25095] Fix for Ti.Media apiName tests

---

Resources/ti.database.test.js
Resources/ti.network.httpclient.test.js
Resources/ti.ui.view.test.js

- Skip `Ti.Database` `execute() returns null instead of empty result set` which is an invalid test
- Allow `Ti.Network.HTTPClient` tests to retry
- Fix `TIMOB-20598` test, which intermittently fails.

Test case fixes

---

Resources/ti.ui.view.test.js

Currently TIMOB-20598 is [failing for Windows](https://jenkins.appcelerator.org/blue/organizations/jenkins/titanium-sdk%2Ftitanium_mobile_windows/detail/PR-1153/1/tests), it seems it is because timeout is too short. I tested it locally and it needs at least 6.5 sec, but the default timeout is 5 sec. Increasing it to 10 sec.

Increase TIMOB-20598 timeout

---

Resources/ti.locale.test.js
Resources/ti.ui.view.test.js

Based on the observation of current failure, I think that [XML tests are failing](https://jenkins.appcelerator.org/blue/organizations/jenkins/titanium-sdk%2Ftitanium_mobile_windows/detail/PR-1152/11/pipeline) because of JavaScript engine issue. I submitted new JavaScriptCore but [it still fails with some other areas](https://jenkins.appcelerator.org/blue/organizations/jenkins/titanium-sdk%2Ftitanium_mobile_windows/detail/PR-1145/13/tests
).  I'm pushing to skip them for now.

Adjust for Windows

---

Resources/app.js
scripts/test.js

Documentation update in appcelerator/titanium_mobile/pull/9511
This PR allows new test files to be added into titanium_mobile or titanium_mobile_windows without the need to copy over the app.js files.
I initially had it as JS files placed under a directory but realised that this made the migration of tests from an SDK repo to here slightly more effort than it should be (replacing `../utilities/assertion` -> `./utilities/assertion`).
It also now cleans up the modules/plugins dirs before and after a run in Jenkins

Autograb files

---

Resources/ti.ui.webview.test.js

The iOS-unit-test for the webview/#loading sometimes failed because the `beforeload` event could also fire for sub-pages and scripts, so we need to guard the value for our test. It also explains why this test only fails sometimes.

iOS: Update ti.ui.webview.test.js

---

Resources/ti.ui.view.test.js
Resources/ti.ui.webview.test.js

We've been seeing unit tests failure on Windows for some new tests like this: [titanium_mobile_windows/detail/PR-1154/16/tests](https://jenkins.appcelerator.org/blue/organizations/jenkins/titanium-sdk%2Ftitanium_mobile_windows/detail/PR-1154/16/tests). Skip them for now to make the build work.

Skip for Windows

---

Resources/ti.ui.textfield.test.js

`focus-blur` in `ti.ui.textfield.test.js` [has been failing for Windows](https://jenkins.appcelerator.org/blue/organizations/jenkins/titanium-sdk%2Ftitanium_mobile_windows/detail/master/230/tests).
As far as I tested, Windows needs some interval before `focus` at `open`.

Windows: Wait for some time before TextField.focus

---

Resources/ti.ui.window.test.js

`window_navigation` test times out on Windows Desktop recently, that blocks current current builds.

Skip window_navigation on Windows Desktop

---

Resources/ti.contacts.test.js

`ti.contacts.getPeopleWithName` is unstable on Windows. Skip it for now.

skip unstable ti.contacts.getPeopleWithName (Windows)

---

Resources/ti.contacts.test.js

JIRA ticket: [TIMOB-23332](https://jira.appcelerator.org/browse/TIMOB-23332)
Skip some tests for Windows because permission prompts hangs UI, just like iOS. I also learned that requesting contact permission from UI thread while blocking the thread actually hangs app:  
Fix - https://github.com/appcelerator/titanium_mobile_windows/pull/1183

[TIMOB-23332] Skip tests for Windows that prompts permission request

---

Resources/ti.network.httpclient.test.js

Re-enable `windowsBroken` HttpClient tests based on the result from https://github.com/appcelerator/titanium_mobile_windows/pull/1188

[TIMOB-25788] Re-enable windowsBroken HttpClient tests

---

Resources/ti.contacts.person.test.js

JIRA ticket: [TIMOB-23332](https://jira.appcelerator.org/browse/TIMOB-23332)
Relates to #42 . Tests against `Contacts.Person` on Windows actually requires permission request and it could hangs the app just like other platforms.

[TIMOB-23332] Skip Contact.Person tests that prompts permission request

---

Resources/ti.ui.label.test.js

Windows `ti.ui.label` `maxLines` failure should be addressed by [TIMOB-25648](https://jira.appcelerator.org/browse/TIMOB-25648).

Remove windowsBroken from maxLines test

---

Resources/ti.network.test.js

This reverts commit 55c695d4a1db0fed9a72506491d25757a84baebe because this is still failing.

Revert (#53)

---

scripts/test.js

Mocha test needs to cleanup `C:\Users\build\.titanium\vsbuild\mocha` before testing because build directory is created under temporary directory on Windows and previous build files (from previous test) could be there.

Clean before building

---

Resources/ti.network.test.js
Resources/ti.ui.window.test.js

Skipping some failing tests for Windows. `Ti.Network.encode/decodeURIComponent` worked locally for me but I don't know why Jenkins is failing for this.

Skip failing tests for Windows

---

Resources/ti.ui.tableview.test.js

TableView on Windows needs some time to construct before finishing.

Wait for TableView before finishing

---

Resources/ti.filesystem.file.test.js

Windows returns empty array for `getDirectoryListing()` for file or non-existent directory. ([TIMOB-26159](https://jira.appcelerator.org/browse/TIMOB-26159))

Skip getDirectoryListing tests that's broken for Windows

---

Resources/ti.ui.tableview.test.js

- Attempt to improve `Titanium.UI.Window` cleanup
- We call `open` to make sure the window is in an open state before we close it to receive the 'close' event

Improve Window cleanup

---

scripts/test.js

This (hopefully) makes it so that when the Titanium build fails, the exit code will bubble through the node script so that it's more obvious where the failure was

Ensure a failed titanium build is reflected through to the script

---

Resources/ti.ui.tableview.test.js

Some TableView tests are failing intermittently on Windows.

Skip unstable TableView tests for Windows

---

scripts/test.js

- Including `<manifest>` with https://github.com/appcelerator/titanium_mobile/pull/10264 causes issues with the generated `tiapp.xml`
- Support both with and without `<manifest>` tags

[TIMOB-26314] Fix manifest tag compatibility

---

Resources/bootstraps/ui.bootstrap.js

Relates to [TIMOB-26457](https://jira.appcelerator.org/browse/TIMOB-26457).
`ui.bootstrap` script exits the app on Windows because of parity issue at `Window.close`.

Skip ui.bootstrap for Windows because of parity issue

---

Resources/ti.ui.tableview.test.js

Skip `delete row (TableViewRow)` test which intermittently crashes for Windows.

Skip failing TableView test for Windows

---

scripts/test.js

Adds a in the tiapp.xml android override that is required for Google Maps API to work when targeting Android 9. This should stop our unit test depending on Ti.Map.View to randomly time out.
https://developers.google.com/maps/documentation/android-sdk/config#specify_requirement_for_apache_http_legacy_library

Fix for unit tests using Ti.Map.View

---

Resources/ti.network.httpclient.test.js

Skip 'send on response' for Windows - "source" property is missing onload

---

scripts/test.js

Relates to: https://github.com/appcelerator/titanium_mobile_windows/pull/1169
Add `--architecture` option so we can target specific architecture. Only valid on Windows.

Add 'architecture' option to specify target architecture

---

Resources/ti.network.httpclient.test.js

We should ignore case in response headers because it seems appcelerator server returns lowercase response header occasionally.

should ignore case in responseHeaders

---

Resources/ti.ui.view.test.js

Skip `animate` tests for Windows. [TIMOB-26791](https://jira.appcelerator.org/browse/TIMOB-26791) should be taking care of it.

Skip TIMOB-26791 tests for Windows

---

Resources/ti.ui.tabgroup.test.js

Wait for for the TabGroup `open` event instead of a Tab's one. That is most likely a typo...

Fix TabGroup "blur" unit test.

---

Resources/ti.xml.test.js

Skip `Titanium.XML` tests for Windows Phone because it's crashing and blocking builds.

fix(windows): skip xml tests for Windows Phone

---

Resources/app.js

https://github.com/appcelerator/titanium_mobile_windows/pull/1376
> This moves the requiring of test files into a function. Then we wait until the window open callback and schedule setup of mocha, loading the test files and then running mocha - all on a setTimeout callback.
> 
> So maybe the initial window will load/open quickly and then fire off the suite async and avoid getting killed off as "hanging" by Windows Desktop?

fix(windows): fix hang at startup on Windows

---

Resources/ti.ui.webview.test.js

Temporarily disabled Ti.UI.WebView ms-appx-data test for Windows because it is unstable.

fix(windows): Temporarily disabled Ti.UI.WebView ms-appx-data test

---

Resources/ti.codec.test.js

skip Codec#encode/decode exception tests for Windows because it's crashing app.

fix(windows): skip Codec#encode/decode exception tests

---

Resources/ti.ui.webview.test.js

This reverts #134. https://github.com/appcelerator/titanium_mobile_windows/pull/1378 should be making the tests more stable.

Revert "fix(windows): Temporarily disabled Ti.UI.WebView ms-appx-data"

---

Resources/ti.ui.layout.test.js
Resources/ti.ui.test.js

- Allow margin of error for specific UI tests that fail use to DPI rounding

fix: approximate failing UI tests

---

plugins/mocha.test.support/hooks/hook.js
scripts/adb-all.sh

- Include `adb-all` script to execute `adb` commands on all connected devices

fix(android): include adb-all script

---

Resources/ti.network.test.js
Resources/ti.ui.label.test.js

ellipsize implemented in https://jira.appcelerator.org/browse/TIMOB-25778
TLS_VERSION constants work locally for me on android/windows, so lets see how it is on Jenkins

test: enable some tests that are no longer failing

---

Resources/ti.ui.textfield.test.js

The `width` test case for `textfield` is not quite right. `rect` should be used when getting actual unit values.

fix: textfield.width test failure

---

Resources/util.test.js

- Allow output from either V8 or JavascriptCore as valid

fix: validate multiple valid outputs for inspect with object

---

Resources/app.js
Resources/ti-mocha.js
Resources/ti.blob.test.js
Resources/ti.map.test.js
Resources/ti.media.videoplayer.test.js
Resources/ti.ui.button.test.js
Resources/ti.ui.imageview.test.js
Resources/ti.ui.label.test.js
Resources/ti.ui.layout.test.js
Resources/ti.ui.listview.test.js
Resources/ti.ui.maskedimage.test.js
Resources/ti.ui.picker.test.js
Resources/ti.ui.scrollableview.test.js
Resources/ti.ui.scrollview.test.js
Resources/ti.ui.searchbar.test.js
Resources/ti.ui.shortcutitem.test.js
Resources/ti.ui.tabbedbar.test.js
Resources/ti.ui.tabgroup.test.js
Resources/ti.ui.tableview.test.js
Resources/ti.ui.test.js
Resources/ti.ui.textarea.test.js
Resources/ti.ui.textfield.test.js
Resources/ti.ui.view.test.js
Resources/ti.ui.webview.test.js
Resources/ti.ui.window.test.js
Resources/ti.utils.test.js

- Improve `Ti.UI.Window` cleanup after tests
- Remove listeners to prevent multiple `finish()` calls
- Warn when `finish()` is called multiple times instead of throwing an error
- Print `!TEST_FAIL` logs when a test fails

chore: improve reliability of tests

---

Resources/ti.filesystem.file.test.js

Skip file test that makes Windows tests unstable for some reason.

test: skip file test that crashes Windows

---

Resources/ti.filesystem.filestream.test.js

Skip filestream tests that makes Jenkins Windows mocha tests unstable.

test: skip unstable filestream tests on Windows

---

Resources/ti.filesystem.filestream.test.js

Attempt to stabilize Windows tests.
filestream pump test should wait for EOF.

test: filestream pump test should wait for EOF

---

Resources/ti.filesystem.filestream.test.js
Resources/ti.ui.tabgroup.test.js

Attemp to stabilize Windows tests
- enable Windows TabGroup test again
- Increase filestream pump timeout

test: enable Windows TabGroup test again

---

scripts/test.js

It seems Windows Update messes some Jenkins builds. We might need to specify installed SDK version instead of using "10.0" as default value.

Force Win10 sdk 10.0.14393 for x86/ARM build

---

Resources/ti.filesystem.file.test.js

Skip URI file tests on Windows because it's broken

fix: skip 'constructed via URIs' tests on Windows

---

Resources/ti.filesystem.file.test.js

fix: skip 'constructed via URIs' tests on Windows (#205)

---

Resources/ti.ui.webview.test.js

Previous URL has an expired cert, this seems to be good for another 6 months
Tested android and ios locally and they both look good, going to see how windows works on jenkins so hold off on the merge I guess

fix: change url for useragent test

---

Jenkinsfile

SDK 9 drops Node 8 support, so we cant use it anymore
Making a PR just to make sure this runs through cleanly and I dont break anything. I'll likely be a naughty chappy and self merge this

ci: use node 10.17.0

---

Resources/ti.ui.picker.test.js

Fixes a typo in DatePicker's minDate test. That was caught with after the change in https://github.com/appcelerator/titanium_mobile/pull/11369

Fix DatePicker minDate test.

---

Resources/app.js

In doing some testing with Android and V8 7.8, I had turned on some extra super low-level logging and found that the test suite was basically generating un-prefixed require paths for add-on tests.
This is an attempt to generate more correct paths (i.e. `'/fs.addontest.js'` vs. `'fs.addontest.js'`)

fix: use absolute require paths for addon tests

---

Resources/ti.network.socket.tcp.test.js

- Remove usage of `pastebin.com` endpoint for TCP tests

chore: remove usage of pastebin endpoint

---

Resources/ti.test.js
plugins/mocha.test.support/hooks/hook.js

**Summary:**
Uses a plugin to fetch the version string used to build the app, store it to app properties, and compare it against `Ti.version` at runtime.
**Note:**
We had a bug in Android where library was wrongly returning "1.0.0" for `Ti.version`.

chore: compare Ti.version with SDK version used

---

Resources/ti.android.test.js
Resources/ti.platform.test.js
scripts/test.js

**Summary:**
- Added 3 `openURL()` tests. Verifies it works by having app open itself
* Verifies it works by having app open itself via "mocha://" custom URL scheme.
* Tests optional arguments such as callback and options dictionary.
- Added `canOpenURL()` test for app's own custom URL scheme.
**Note:**
Do not merge this PR until the following Titanium SDK PRs have been merged...
- https://github.com/appcelerator/titanium_mobile/pull/11655
- https://github.com/appcelerator/titanium_mobile/pull/11668

chore: added Ti.Platform.openURL() tests
